-- ==========================================
-- SCRIPT DE CREACIÓN DE BASE DE DATOS (SUPABASE)
-- ==========================================
-- Este script contiene únicamente la estructura de las tablas,
-- sin registros ni datos iniciales.

-- 1. Tabla de Usuarios (Users)
-- Almacena administradores, clientes (SaaS) y superadmins.
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT DEFAULT 'admin',
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Tabla de Eventos
-- Cada evento pertenece a un cliente específico.
CREATE TABLE eventos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  fecha TIMESTAMP WITH TIME ZONE,
  precio_boleta NUMERIC DEFAULT 0,
  cliente_id BIGINT REFERENCES users(id), -- Relación con el creador del evento
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Tabla de Asistentes
-- Almacena las boletas y registros de las personas que asisten a un evento.
CREATE TABLE asistentes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  documento TEXT NOT NULL,
  telefono TEXT NOT NULL,
  email TEXT,
  metodo_pago TEXT NOT NULL,
  monto NUMERIC NOT NULL,
  fecha_pago TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  comprobante TEXT,
  estado TEXT DEFAULT 'no_presente', -- 'no_presente' o 'presente'
  hora_ingreso TIMESTAMP WITH TIME ZONE,
  qr_token TEXT UNIQUE NOT NULL,
  evento_id BIGINT REFERENCES eventos(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- RESTRICCIONES ADICIONALES Y MEJORAS
-- ==========================================
-- Evitar que un mismo documento compre dos veces en el MISMO evento
ALTER TABLE asistentes ADD CONSTRAINT unique_doc_per_event UNIQUE (documento, evento_id);
